export const SEO_CONFIG = {
  siteUrl: process.env.NEXT_PUBLIC_SITE_URL || 'https://brisbanecarpetpestexperts.com.au',
  siteName: process.env.NEXT_PUBLIC_SITE_NAME || 'Brisbane Carpet & Pest Experts',
  siteDescription:
    process.env.NEXT_PUBLIC_SITE_DESCRIPTION ||
    'Brisbane’s trusted experts for bond cleaning, end of lease cleaning, carpet steam cleaning, upholstery cleaning, and pest control. 100% Bond Back Guarantee.',
  twitterHandle: '@brisbanecarpet',
  defaultImage: '/images/home-clean.jpg',
  defaultImageAlt: 'Brisbane Carpet & Pest Experts - Professional Cleaning & Pest Control',
  robots: 'index, follow',
  googleSiteVerification: process.env.NEXT_PUBLIC_GOOGLE_SITE_VERIFICATION || '',
  keywords: [
    'carpet cleaning brisbane',
    'bond cleaning brisbane',
    'end of lease cleaning brisbane',
    'pest control brisbane',
    'carpet steam cleaning',
    'upholstery cleaning brisbane',
    'tile and grout cleaning brisbane',
    'exit clean brisbane',
    'vacate cleaning brisbane',
    'pest treatment brisbane',
    'flea treatment brisbane bond',
    'commercial cleaning brisbane',
    'cheap carpet cleaning brisbane',
    'emergency cleaning brisbane',
  ],
};

export const COMPANY_INFO = {
  name: 'Brisbane Carpet & Pest Experts',
  legalName: 'Brisbane Carpet & Pest Experts Pty Ltd',
  email: 'info@brisbanecarpetpestexperts.com.au',
  phone: '0434 061 188',
  phoneRaw: '+61434061188',
  address: '192 Turton St, Sunnybank, QLD 4109, Brisbane, Australia',
  streetAddress: '192 Turton St',
  suburb: 'Sunnybank',
  state: 'QLD',
  postcode: '4109',
  country: 'AU',
  openingHours: 'Mo-Su 07:00-19:00',
  social: {
    twitter: 'https://twitter.com/brisbanecarpet',
    facebook: 'https://facebook.com/brisbanecarpetpestexperts',
    instagram: 'https://instagram.com/brisbanecarpetpestexperts',
    linkedin: 'https://linkedin.com/company/brisbanecarpetpestexperts',
    youtube: 'https://youtube.com/@brisbanecarpetpestexperts',
  },
};
